*******************************
* Standardises Country Names and Matches them with their IMF Country Code
* Created by Christopher Gandrud 
* Updated 28 January 2012
*******************************       



gen imfcode = .
replace country = "Afghanistan" if country == "Afghanistan, Rep. of."
replace country = "Afghanistan" if country == "afghanistan"
replace imfcode = 512 if country =="Afghanistan"
replace country = "Albania" if country == "albania"
replace country = "Albania" if country == "AL"
replace imfcode = 914 if country =="Albania"
replace country = "Algeria" if country == "algeria"
replace country = "Algeria" if country == "DZ"
replace imfcode = 612 if country =="Algeria"
replace country = "American Samoa" if country == "am_samoa"
replace imfcode = 859 if country =="American Samoa"
replace country = "Andorra" if country == "AD"
replace country = "Angola" if country == "angola"
replace imfcode = 614 if country =="Angola"
replace country = "Antigua and Barbuda" if country == "antigua_barb"
replace country = "Antigua and Barbuda" if country == "Antigua & Barbuda"
replace country = "Antigua and Barbuda" if country == "Antigua and Barbuba"
replace country = "Antigua and Barbuda" if country == "AntiguaandBarbuda"
replace imfcode = 311 if country =="Antigua and Barbuda"
replace country = "Argentina" if country == "argentina"
replace country = "Argentina" if country == "AR"
replace country = "Argentina" if country == "argentina"
replace country = "Argentina" if country == "argentin"
replace country = "Argentina" if country == "ARGENTINA"
replace imfcode = 213 if country =="Argentina"
replace country = "Armenia" if country == "armenia"
replace country = "Armenia" if country == "AM"
replace imfcode = 911 if country =="Armenia"
replace country = "Australia" if country == "AUSTRALIA"
replace country = "Australia" if country == "australia"
replace country = "Australia" if country == "AU"
replace imfcode = 193 if country =="Australia"
replace country = "Austria" if country == "AUSTRIA"
replace country = "Austria" if country == "austria"
replace imfcode = 122 if country =="Austria"
replace country = "Aruba" if country == "aruba"
replace imfcode = 314 if country =="Aruba"
replace country = "Azerbaijan" if country == "azerbaijan"
replace country = "Azerbaijan" if country == "AZ"
replace imfcode = 912 if country =="Azerbaijan"
replace country = "Bahamas" if country == "bahamas"
replace country= "Bahamas" if country == "Bahamas, The"
replace country= "Bahamas" if country == "Bahamas,The"  
replace country= "Bahamas" if country == " Bahamas, The " 
replace imfcode = 313 if country =="Bahamas"
replace country = "Bahrain" if country == "bahrain"
replace imfcode = 419 if country =="Bahrain"
replace country = "Bangladesh" if country == "bangladesh"
replace country = "Bangladesh" if country == "BD"
replace imfcode = 513 if country =="Bangladesh"
replace country = "Barbados" if country == "barbados"
replace imfcode = 316 if country =="Barbados"
replace country = "Belarus" if country == "Belarus (Byelorussia)"
replace country = "Belarus" if country == "belarus"
replace country = "Belarus" if country == "BY"
replace imfcode = 913 if country =="Belarus"
replace country = "Belgium" if country == "belgium"
replace country = "Belgium" if country == "BELGIUM"
replace imfcode = 124 if country =="Belgium"
replace country = "Belize" if country == "belize"
replace imfcode = 339 if country =="Belize"
replace country = "Benin" if country == "benin"
replace imfcode = 638 if country =="Benin"
replace country = "Bermuda" if country == "bermuda"
replace imfcode = 319 if country =="Bermuda"
replace country = "Bhutan" if country == "bhutan"
replace imfcode = 514 if country =="Bhutan"
replace country = "Bolivia" if country == "bolivia"
replace imfcode = 218 if country =="Bolivia"
replace country = "Bosnia and Herzegovina" if country == "bosnia_herzeg"
replace country = "Bosnia and Herzegovina" if country == "BA"
replace country = "Bosnia and Herzegovina" if country == "bosnia"
replace country = "Bosnia and Herzegovina" if country == "Bosnia"
replace country = "Bosnia and Herzegovina" if country == "Bosnia-Herz"
replace country = "Bosnia and Herzegovina" if country == "Bosnia-Herzegovina"
replace country = "Bosnia and Herzegovina" if country == "BosniaandHerzegovina"
replace country = "Bosnia and Herzegovina" if country == "Bosnia & Herzegovina"
replace imfcode = 963 if country == "Bosnia and Herzegovina"
replace country = "Botswana" if country == "botswana"
replace imfcode = 616 if country =="Botswana"
replace country = "Brazil" if country == "brazil"
replace country = "Brazil" if country == "BRAZIL"
replace country = "Brazil" if country == "BR"
replace imfcode = 223 if country =="Brazil"
replace country = "Brunei Darussalam" if country == "Brunei"
replace country = "Brunei Darussalam" if country == "BruneiDarussalam"
replace country = "Brunei Darussalam" if country == "brunei"
replace imfcode = 516 if country =="Brunei Darussalam"
replace country = "Bulgaria" if country == "bulgaria"
replace country = "Bulgaria" if country == "BG"
replace imfcode = 918 if country =="Bulgaria"
replace country = "Burkina Faso" if country == "Burkina Faso (Upper Volta)"
replace country = "Burkina Faso" if country == "burkina_faso"
replace country = "Burkina Faso" if country == "burkinafaso"
replace country = "Burkina Faso" if country == "BurkinaFaso"
replace country = "Burkina Faso" if country == "BF"
replace imfcode = 748 if country =="Burkina Faso"
replace country = "Burundi" if country == "burundi"
replace imfcode = 618 if country =="Burundi"
replace country = "Cambodia" if country == "cambodia"
replace imfcode = 522 if country =="Cambodia"
replace country = "Cameroon" if country == "cameroon"
replace imfcode = 622 if country =="Cameroon"
replace country = "Canada" if country == "canada"
replace country = "Canada" if country == "CANADA"
replace country = "Canada" if country == "CA"
replace imfcode = 156 if country =="Canada"
replace country = "Cape Verde" if country == "C. Verde Is."
replace country = "Cape Verde" if country == "cape_verde"
replace country = "Cape Verde" if country == "capeverde"
replace country = "Cape Verde" if country == "CapeVerde"
replace imfcode = 624 if country =="Cape Verde"
replace country = "Cayman Islands" if country == "cayman_is"
replace country = "Cayman Islands" if country == "CaymanIslands"
replace imfcode = 377 if country =="Cayman Islands"
replace country = "Central African Republic" if country == "car"
replace country = "Central African Republic" if country == "Cen African Rep"
replace country = "Central African Republic" if country == "Cent. Af. Rep."
replace country = "Central African Republic" if country == "Central African Rep."
replace country = "Central African Republic" if country == "CentralAfricanRepublic"
replace imfcode = 626 if country =="Central African Republic"
replace country = "Chad" if country == "chad"
replace imfcode = 628 if country =="Chad"
replace country = "Chile" if country == "CHILE"
replace country = "Chile" if country == "CL"
replace country = "Chile" if country == "chile"
replace imfcode = 228 if country =="Chile"
replace country = "China" if country == "PRC"
replace country = "China" if country == "china"
replace country = "China" if country == "CN"
replace country = "China" if country == "China, P.R."
replace imfcode = 924 if country =="China"
replace country = "Colombia" if country == "COLOMBIA"
replace country = "Colombia" if country == "CO"
replace country = "Colombia" if country == "colombia"
replace imfcode = 233 if country =="Colombia"
replace country = "Comoros" if country == "Comoro Is."
replace country = "Comoros" if country == "comoros"
replace country = "Comoros" if country == "comoroislands"
replace imfcode = 632 if country =="Comoros"
replace country = "Congo, Dem. Rep." if country == "Congo, Dem. Rep. of"
replace country = "Congo, Dem. Rep." if country == "Congo,Dem.Rep."
replace country = "Congo, Dem. Rep." if country == "congo__dem_"
replace country = "Congo, Dem. Rep." if country == "zairecongokinshasa"
replace country = "Congo, Dem. Rep." if country == "Congo Kinshasa"
replace country = "Congo, Dem. Rep." if country == "Congo, Kinshasa"
replace country = "Congo, Dem. Rep." if country == "Congo, Dem. Rep."
replace country = "Congo, Dem. Rep." if country == " Congo, Dem. Rep. "
replace country = "Congo, Dem. Rep." if country == "Congo, DR"
replace country = "Congo, Dem. Rep." if country == "zaire"
replace country = "Congo, Dem. Rep." if country == "Zaire"
replace country = "Congo, Dem. Rep." if country == "Congo, Democratic Republic of (Zaire)"
replace country = "Congo, Dem. Rep." if country == "Congo, Dem. Rep. (Zaire)"
replace country = "Congo, Dem. Rep." if country == "Congo, Democratic Republic of"
replace country = "Congo, Dem. Rep." if country == "Zaire (Democ Republic Congo)"
replace country = "Congo, Dem. Rep." if country == "Congo, Dem. Rep. "
replace imfcode = 636 if country == "Congo, Dem. Rep."
replace country = "Congo, Rep." if country == "congo__rep_"
replace country = "Congo, Rep." if country == "Congo"
replace country = "Congo, Rep." if country == " Congo, Rep. "
replace country = "Congo, Rep." if country == "Congo,Rep."
replace country = "Congo, Rep." if country == "Congo Brazzaville"
replace country = "Congo, Rep." if country == "Congo, Brazzaville"
replace country = "Congo, Rep." if country == "congobrazzaville"
replace country = "Congo, Rep." if country == "Republic of Congo"
replace country = "Congo, Rep." if country == "Congo, Rep. of"
replace country = "Congo, Rep." if country == "Congo, Republic of"
replace imfcode = 634 if country =="Congo, Rep."
replace country = "Costa Rica" if country == "COSTA RICA"
replace country = "Costa Rica" if country == "costa_rica"
replace country = "Costa Rica" if country == "costarica"
replace country = "Costa Rica" if country == "CostaRica"
replace imfcode = 238 if country =="Costa Rica"
replace country = "Cote dIvoire" if country == "Cote d'Ivoire"
replace country = "Cote dIvoire" if country == "Coted'Ivoire"
replace country = "Cote dIvoire" if country == "Ivory Coast"
replace country = "Cote dIvoire" if country == "cote_d_ivoire"
replace country = "Cote dIvoire" if country == "Cote DIvoire"
replace country = "Cote dIvoire" if country == "COTE D'IVOIRE"
replace country = "Cote dIvoire" if country == "CÙte d'Ivoire"
replace country = "Cote dIvoire" if country == "Cote D∆Ivoire"
replace country = "Cote dIvoire" if country == "CÙte díIvoire"
replace country = "Cote dIvoire" if country == "Côte d'Ivoire"
replace country = "Cote dIvoire" if country == "ctedivoire"
replace imfcode = 662 if country =="Cote dIvoire"
replace country = "Croatia" if country == "croatia"
replace country = "Croatia" if country == "HR"
replace imfcode = 960 if country =="Croatia"
replace country = "Cuba" if country == "cuba"
replace imfcode = 928 if country =="Cuba"
replace country = "Cyprus" if country == "Greek Cyprus"
replace country = "Cyprus" if country == "cyprus"
replace country = "Cyprus" if country == "CY"
replace imfcode = 423 if country =="Cyprus"
replace country = "Czechoslovakia" if country == "Czechoslovakia"
replace country = "Czech Republic" if country == "Czech Rep."
replace country = "Czech Republic" if country == "CZ"
replace country = "Czech Republic" if country == "CzechRepublic"
replace country = "Czech Republic" if country == "czech_rep"
replace country = "Czech Republic" if country == "czechrep"
replace imfcode = 935 if country =="Czech Republic"
replace country = "Denmark" if country == "denmark"
replace country = "Denmark" if country == "DENMARK"
replace imfcode = 128 if country =="Denmark"
replace country = "Djibouti" if country == "djibouti"
replace imfcode = 611 if country =="Djibouti"
replace country = "Dominica" if country == "dominica"
replace imfcode = 321 if country =="Dominica"
replace country = "Dominican Republic" if country == "Dom. Rep."
replace country = "Dominican Republic" if country == "DO"
replace country = "Dominican Republic" if country == "dominican_rep"
replace country = "Dominican Republic" if country == "dominicanrep"
replace country = "Dominican Republic" if country == "Dominican Rep"
replace country = "Dominican Republic" if country == "DominicanRepublic"
replace imfcode = 243 if country =="Dominican Republic"
replace country = "Ecuador" if country == "ecuador"
replace country = "Ecuador" if country == "ECUADOR"
replace imfcode = 248 if country =="Ecuador"
replace country = "Egypt" if country == "egypt"
replace country = "Egypt" if country == "Egypt, Arab Rep."
replace country = "Egypt" if country == "Egypt,ArabRep."
replace country = "Egypt" if country == " Egypt, Arab Rep. "
replace country = "Egypt" if country == "EGYPT"
replace country = "Egypt" if country == "EG"
replace imfcode = 469 if country =="Egypt"
replace country = "El Salvador" if country == "el_salvador"
replace country = "El Salvador" if country == "elsalvador"
replace country = "El Salvador" if country == "ElSalvador"
replace country = "El Salvador" if country == "SV"
replace imfcode = 253 if country =="El Salvador"
replace country = "Equatorial Guinea" if country == "equat_guinea"
replace country = "Equatorial Guinea" if country == "equatorialguinea"
replace country = "Equatorial Guinea" if country == "EquatorialGuinea"
replace country = "Equatorial Guinea" if country == "Eq. Guinea"
replace imfcode = 642 if country =="Equatorial Guinea"
replace country = "Eritrea" if country == "eritrea"
replace imfcode = 643 if country =="Eritrea"
replace country = "Estonia" if country == "estonia"
replace country = "Estonia" if country == "EE"
replace imfcode = 939 if country =="Estonia"
replace country = "Ethiopia" if country == "ethiopia"
replace country = "Ethiopia" if country == "ET"
replace country = "Ethiopia" if country == "eritreaethiopia"
replace imfcode = 644 if country =="Ethiopia"
replace country = "Faeroe Islands" if country == "faeroe_is"
replace imfcode = 816 if country =="Faeroe Islands"
replace country = "Fiji" if country == "fiji"
replace imfcode = 819 if country =="Fiji"
replace country = "Finland" if country == "finland"
replace country = "Finland" if country == "FI"
replace country = "Finland" if country == "FINLAND"
replace imfcode = 172 if country =="Finland"
replace country = "France" if country == "france"
replace country = "France" if country == "FRANCE"
replace country = "France" if country == "FR"
replace imfcode = 132 if country =="France"
replace country = "French Polynesia" if country == "french_poly"
replace country = "French Polynesia" if country == "FrenchPolynesia"
replace imfcode = 887 if country =="French Polynesia"
replace country = "Gabon" if country == "gabon"
replace imfcode = 646 if country =="Gabon"
replace country = "Gambida" if country == "gambia"
replace country = "Gambia" if country =="Gambia, The"
replace country = "Gambia" if country =="Gambia,The"
replace country = "Gambia" if country =="Gambia, The "
replace country = "Gambia" if country ==" Gambia, The "
replace imfcode = 648 if country =="Gambia"
replace country = "Georgia" if country == "georgia"
replace country = "Georgia" if country == "GE"
replace imfcode = 915 if country =="Georgia"
replace country = "GDR" if country == "germany_east"
replace country = "East Germany" if country == "Germany East"
replace country = "East Germany" if country == "GDR"
replace country = "Germany" if country == "germany"
replace country = "Germany" if country == "FRG/Germany"
replace country = "Germany" if country == "Germany West"
replace country = "Germany" if country == "DE"
replace country = "Germany" if country == "German Federal Republic"
replace country = "Germany" if country == "GERMANY"
replace imfcode = 134 if country =="Germany"
replace country = "Ghana" if country == "ghana"
replace country = "Ghana" if country == "GHANA"
replace country = "Ghana" if country == "GH"
replace imfcode = 652 if country =="Ghana"
replace country = "Gibraltar" if country == "gibraltar"
replace imfcode = 823 if country == "Gibraltar"
replace country = "Greece" if country == "greece"
replace country = "Greece" if country == "GREECE"
replace imfcode = 174 if country =="Greece"
replace country = "Greenland" if country == "greenland"
replace imfcode = 326 if country =="Greenland"
replace country = "Grenada" if country == "grenada"
replace imfcode = 328 if country =="Grenada"
replace country = "Guam" if country == "guam"
replace imfcode = 829 if country =="Guam"
replace country = "Guatemala" if country == "guatemala"
replace country = "Guatemala" if country == "GT"
replace imfcode = 258 if country =="Guatemala"
replace country = "Guinea" if country == "guinea"
replace imfcode = 656 if country =="Guinea"
replace country = "Guinea Bissau" if country == "guinea_bissau"
replace country = "Guinea Bissau" if country == "guineabissau"
replace country = "Guinea Bissau" if country =="Guinea-Bissau"
replace imfcode = 654 if country =="Guinea Bissau"
replace country = "Guyana" if country == "guyana"
replace imfcode = 336 if country =="Guyana"
replace country = "Haiti" if country == "haiti"
replace country = "Haiti" if country == "hati"
replace imfcode = 263 if country =="Haiti"
replace country = "Honduras" if country == "honduras"
replace imfcode = 268 if country =="Honduras"
replace country = "Hong Kong" if country == "hong_kong"
replace country = "Hong Kong" if country == "HK"
replace country = "Hong Kong" if country == "hongkong"
replace country = "Hong Kong" if country == "HONG KONG"
replace country = "Hong Kong" if country == "Hongkong"
replace country = "Hong Kong" if country == "Hong Kong, China"
replace country = "Hong Kong" if country == " Hong Kong, China "
replace country = "Hong Kong" if country == "Hong Kong SAR, China"
replace country = "Hong Kong" if country == "HongKongSAR,China"
replace country = "Hong Kong" if country == "Hong Kong SAR"
replace country = "Hong Kong" if country == "China, P.R.: Hong Kong"
replace imfcode = 532 if country =="Hong Kong"
replace country = "Hungary" if country == "hungary"
replace country = "Hungary" if country == "HU"
replace imfcode = 944 if country =="Hungary"
replace country = "Iceland" if country == "iceland"
replace country = "Iceland" if country == "ICELAND"
replace imfcode = 176 if country =="Iceland"
replace country = "India" if country == "india"
replace country = "India" if country == "INDIA"
replace country = "India" if country == "IN"
replace imfcode = 534 if country =="India"
replace country = "Indonesia" if country == "indonesia"
replace country = "Indonesia" if country == "INDONESIA"
replace country = "Indonesia" if country == "ID"
replace imfcode = 536 if country =="Indonesia"
replace country = "Iran" if country == "Iran, Islamic Rep."
replace country = "Iran" if country == "IR"
replace country = "Iran" if country == "Iran,IslamicRep."
replace country = "Iran" if country == " Iran, Islamic Rep. "
replace country = "Iran" if country == "iran"
replace country = "Iran" if country == "Iran, Islamic Rep. of"
replace country = "Iran" if country == "Iran, Islamic Republic of"
replace country = "Iran" if country == "Iran, I.R. of"
replace country = "Iran" if country == "Iran (Persia)"
replace imfcode = 429 if country =="Iran"
replace country = "Iraq" if country == "iraq"
replace country = "Iraq" if country == "IQ"
replace imfcode = 433 if country =="Iraq"
replace country = "Ireland" if country == "ireland"
replace country = "Ireland" if country == "IRELAND"
replace imfcode = 178 if country =="Ireland"
replace country = "Isle of Man" if country == "isle_of_man"
replace imfcode = . if country =="Isle of Man"
replace country = "Israel" if country == "ISRAEL"
replace country = "Israel" if country == "IL"
replace country = "Israel" if country == "israel"
replace imfcode = 436 if country =="Israel"
replace country = "Italy" if country == "Italy/Sardinia"
replace country = "Italy" if country == "italy"
replace country = "Italy" if country == "ITALY"
replace country = "Italy" if country == "IT"
replace imfcode = 136 if country =="Italy"
replace country = "Jamaica" if country == "jamaica"
replace country = "Jamaica" if country == "JAMAICA"
replace imfcode = 343 if country =="Jamaica"
replace country = "Japan" if country == "japan"
replace country = "Japan" if country == "JAPAN"
replace country = "Japan" if country == "JP"
replace imfcode = 158 if country =="Japan"
replace country = "Jordan" if country == "jordan"
replace country = "Jordan" if country == "JORDAN"
replace country = "Jordan" if country == "JO"
replace imfcode = 439 if country =="Jordan"
replace country = "Kazakstan" if country == "kazakhstan"
replace imfcode = 916 if country =="Kazakhstan"
replace country = "Kenya" if country == "kenya"
replace country = "Kenya" if country == "KENYA"
replace imfcode = 664 if country =="Kenya"
replace country = "Kirabati" if country == "kiribati"
replace imfcode = 826 if country =="Kiribati"
replace country = "North Korea" if country == "PRK"
replace country = "North Korea" if country == "Korea, North"
replace country = "North Korea" if country == "Korea,Dem.Rep."
replace country = "Korea" if country == "ROK"
replace country = "Korea" if country == "korea"
replace country = "Korea" if country == "Korea, Republic of"
replace country = "Korea" if country == "Korea Republic"
replace country = "Korea" if country == "Korea South"
replace country = "Korea" if country == "Korea, Rep."
replace country = "Korea" if country == "Korea,Rep."
replace country = "Korea" if country == " Korea, Rep. "
replace country = "Korea" if country == "KR"
replace country = "Korea" if country == "Korea, Rep. of"
replace country = "Korea" if country == "Korea Rep"
replace country = "Korea" if country == "Korea, South"
replace country = "Korea" if country == "KOREA"
replace country = "Korea" if country == "KOREA REP. OF"
replace imfcode = 542 if country =="Korea"
replace country = "Kuwait" if country == "kuwait"
replace imfcode = 443 if country =="Kuwait"
replace country = "Kyrgyz Republic" if country == "kyrgyz_rep"
replace country = "Kyrgyz Republic" if country == "KG"
replace country = "Kyrgyz Republic" if country == "KyrgyzRepublic"
replace country = "Kyrgyz Republic" if country == "kyrgyzstan"
replace country = "Kyrgyz Republic" if country == "Kyrgyzstan"
replace imfcode = 917 if country =="Kyrgyz Republic"
replace country = "Laos" if country == "lao"
replace country = "Laos" if country == "Lao People's Dem Rep"
replace country = "Laos" if country == "laos"
replace country = "Laos" if country == "Lao PDR"
replace country = "Laos" if country == "LaoPDR"
replace country = "Laos" if country == "Lao P.D.R."
replace country = "Laos" if country == "Lao Peopleís Dem. Rep."
replace country = "Laos" if country == "Lao People's Democratic Republic"
replace imfcode = 544 if country =="Laos"
replace country = "Latvia" if country == "latvia"
replace country = "Latvia" if country == "LV"
replace imfcode = 941 if country =="Latvia"
replace country = "Lebanon" if country == "lebanon"
replace imfcode = 446 if country =="Lebanon"
replace country = "Lesotho" if country == "lesotho"
replace imfcode = 666 if country =="Lesotho"
replace country = "Liberia" if country == "liberia"
replace imfcode = 668 if country =="Liberia"
replace country = "Libya" if country == "libya"
replace imfcode = 672 if country =="Libya"
replace country = "Lithuania" if country == "lithuania"
replace country = "Lithuania" if country == "LT"
replace imfcode = 946 if country =="Lithuania"
replace country = "Luxembourg" if country == "luxembourg"
replace country = "Luxembourg" if country == "Luxemburg"
replace imfcode = 137 if country =="Luxembourg"
replace country = "Macao" if country == "macao"
replace country= "Macao" if country=="Macao, China"
replace country= "Macao" if country=="Macau"
replace country= "Macao" if country=="Macao SAR, China"
replace country= "Macao" if country=="MacaoSAR,China"
replace imfcode = 546 if country =="Macao"
replace country = "Macedonia" if country == "macedonia"
replace country = "Macedonia" if country == "Macedonia (Former Yug. Rep)"
replace country = "Macedonia" if country == "MK"
replace country = "Macedonia" if country == "Macedonia, FYR"
replace country = "Macedonia" if country == "Macedonia,FYR"
replace country = "Macedonia" if country == " Macedonia, FYR "
replace country = "Macedonia" if country == "Macedonia FYR"
replace country = "Macedonia" if country == "Macedonia, Former Yugoslav Republic of"
replace imfcode = 962 if country =="Macedonia"
replace country = "Madagascar" if country == "madagascar"
replace country = "Madagascar" if country == "Madagascar (Malagasy)"
replace imfcode = 674 if country =="Madagascar"
replace country = "Malawi" if country == "malawi"
replace imfcode = 676 if country =="Malawi"
replace country = "Malaysia" if country == "malaysia"
replace country = "Malaysia" if country == "MALAYSIA"
replace country = "Malaysia" if country == "MY"
replace imfcode = 548 if country =="Malaysia"
replace country = "Maldives" if country == "maldives"
replace imfcode = 556 if country =="Maldives"
replace country = "Mali" if country == "mali"
replace country = "Mali" if country == "ML"
replace imfcode = 678 if country =="Mali"
replace country = "Malta" if country == "malta"
replace imfcode = 181 if country =="Malta"
replace country = "Marshall Islands" if country == "marshall_is"
replace country = "Marshall Islands" if country == "MarshallIslands"
replace imfcode = 867 if country =="Marshall Islands"
replace country = "Mauritania" if country == "mauritania"
replace imfcode = 682 if country =="Mauritania"
replace country = "Mauritius" if country == "mauritius"
replace imfcode = 684 if country =="Mauritius"
replace country = "Mexico" if country == "mexico"
replace country = "Mexico" if country == "MX"
replace country = "Mexico" if country == "MEXICO"
replace imfcode = 273 if country =="Mexico"
replace country = "Micronesia" if country == "micronesia"
replace country = "Micronesia" if country == "Micronesia, Fed. Sts."
replace country = "Micronesia" if country == "Micronesia,Fed.Sts."
replace country = "Micronesia" if country == " Micronesia, Fed. Sts. "
replace country = "Micronesia" if country == "Micronesia, Fed. States of"
replace country = "Micronesia" if country == "Micronesia, Fed Stat"
replace imfcode = 868 if country =="Micronesia"
replace country = "Moldova" if country == "moldova"
replace country = "Moldova" if country == "MD"
replace imfcode = 921 if country =="Moldova"
replace country = "Mongolia" if country == "mongolia"
replace imfcode = 948 if country =="Mongolia"
replace country = "Montenegro" if country == "montenegro"
replace imfcode = 943 if country =="Montenegro"
replace country = "Morocco" if country == "morocco"
replace country = "Morocco" if country == "MA"
replace imfcode = 686 if country =="Morocco"
replace country = "Mozambique" if country == "mozambique"
replace imfcode = 688 if country =="Mozambique"
replace country = "Mayanmar" if country == "myanmar"
replace country = "Mayanmar" if country == "burma"
replace country = "Myanmar" if country == "Myanmar (Burma)"
replace imfcode = 518 if country =="Myanmar"
replace country = "Namibia" if country == "namibia"
replace imfcode = 728 if country =="Namibia"
replace country = "Nepal" if country == "nepal"
replace imfcode = 558 if country =="Nepal"
replace country = "Netherlands" if country == "netherlands"
replace country = "Netherlands" if country == "NL"
replace country = "Netherlands" if country == "Netherlands, The"
replace country = "Netherlands" if country == "NETHERLANDS"
replace imfcode = 138 if country =="Netherlands"
replace country = "Netherlands Antilles" if country == "netherlands_antilles"
replace imfcode = 353 if country =="Netherlands Antilles"
replace country = "New Caledonia" if country == "new_caledonia"
replace country = "New Caledonia" if country == "NewCaledonia"
replace imfcode = 839 if country =="new_caledonia"
replace country = "New Zealand" if country == "new_zealand"
replace country = "New Zealand" if country == "NZ"
replace country = "New Zealand" if country == "NewZealand"
replace country = "New Zealand" if country == "newzealand"
replace country = "New Zealand" if country == "NEW ZEALAND"
replace imfcode = 196 if country =="New Zealand"
replace country = "Nicaragua" if country == "nicaragua"
replace imfcode = 278 if country =="Nicaragua"
replace country = "Niger" if country == "niger"
replace imfcode = 692 if country =="Niger"
replace country = "Nigeria" if country == "nigeria"
replace country = "Nigeria" if country == "NIGERIA"
replace country = "Nigeria" if country == "NG"
replace imfcode = 694 if country =="Nigeria"
replace country = "Norway" if country == "norway"
replace country = "Norway" if country == "NORWAY"
replace country = "Norway" if country == "NO"
replace imfcode = 142 if country =="Norway"
replace country = "Oman" if country == "oman"
replace imfcode = 449 if country =="Oman"
replace country = "Pakistan" if country == "pakistan"
replace country = "Pakistan" if country == "PAKISTAN"
replace country = "Pakistan" if country == "PK"
replace imfcode = 564 if country =="Pakistan"
replace country = "Palau" if country == "palau"
replace imfcode = 565 if country =="Palau"
replace country = "Panama" if country == "panama"
replace imfcode = 283 if country =="Panama"
replace country = "Papua New Guinea" if country == "papua_new_g_"
replace country = "Papua New Guinea" if country == "P. N. Guinea"
replace country = "Papua New Guinea" if country == "PapuaNewGuinea"
replace imfcode = 853 if country =="Papua New Guinea"
replace country = "Paraguay" if country == "paraguay"
replace country = "Paraguay" if country == "PARAGUAY"
replace imfcode = 288 if country =="Paraguay"
replace country = "Peru" if country == "peru"
replace country = "Peru" if country == "PE"
replace country = "Peru" if country == "PERU"
replace imfcode = 293 if country =="Peru"
replace country = "Philippines" if country == "philippines"
replace country = "Philippines" if country == "PH"
replace country = "Philippines" if country == "PHILIPPINES"
replace country = "Philippines" if country == "PH"
replace imfcode = 566 if country =="Philippines"
replace country = "Poland" if country == "poland"
replace country = "Poland" if country == "PL"
replace imfcode = 964 if country =="Poland"
replace country = "Portugal" if country == "portugal"
replace country = "Portugal" if country == "PORTUGAL"
replace imfcode = 182 if country =="Portugal"
replace country = "Puerto Rico" if country == "puerto_rico"
replace country = "Puerto Rico" if country == "puertorico"
replace country = "Puerto Rico" if country == "PuertoRico"
replace country = "Puerto Rico" if country == "PR"
replace imfcode = . if country =="Puerto Rico"
replace country = "Qatar" if country == "qatar"
replace imfcode = 453 if country =="Qatar"
replace country = "Romania" if country == "romania"
replace country = "Romania" if country == "RO"
replace imfcode = 968 if country =="Romania"
replace country = "Russian Federation" if country == "russia"
replace country = "Russian Federation" if country == "RU"
replace country = "Russian Federation" if country == "Russia (Soviet Union)"
replace country = "Russian Federation" if country == "Russia (USSR)"
replace country = "Russian Federation" if country == "Russia"
replace country = "Russian Federation" if country == "RussianFederation"
replace imfcode = 922 if country =="Russian Federation"
replace country = "Rwanda" if country == "rwanda"
replace country = "Rwanda" if country == "RW"
replace imfcode = 714 if country =="Rwanda"
replace country = "Samoa" if country == "samoa"
replace country = "Samoa" if country == "Samoa/Western Samoa"
replace imfcode = 862 if country =="Samoa"
replace country = "San Marino" if country == "san_marino"
replace imfcode = 135 if country =="San Marino"
replace country = "Sao Tome and Principe" if country == "sao_tome_pr"
replace country = "Sao Tome and Principe" if country == "São TomÅEand Principe"
replace country = "Sao Tome and Principe" if country == "SaoTomeandPrincipe"
replace country = "Sao Tome and Principe" if country == "Sao Tome"
replace country = "Sao Tome and Principe" if country == "stomp"
replace country = "Sao Tome and Principe" if country == "S„o TomÈ and Principe"
replace country = "Sao Tome and Principe" if country == "S„o TomÈ & PrÌncipe"
replace imfcode = 716 if country =="Sao Tome and Principe"
replace country = "Saudi Arabia" if country == "saudi_arabia"
replace country = "Saudi Arabia" if country == "saudiarabia"
replace country = "Saudi Arabia" if country == "SaudiArabia"
replace country = "Saudi Arabia" if country == "SA"
replace imfcode = 456 if country =="Saudi Arabia"
replace country = "Senegal" if country == "senegal"
replace country = "Senegal" if country == "SENEGAL"
replace imfcode = 722 if country =="Senegal"
replace country = "Serbia" if country == "serbia"
replace country = "Serbia" if country == "CS"
replace country = "Serbia" if country == "CSS"
replace country = "Serbia" if country == "Yugoslavia (Serbia)"
replace country = "Serbia" if country == "Serbia & Montenegro"
replace country = "Serbia" if country == "Serbia and Montenegro"
replace imfcode = 965 if country =="Serbia"
replace country = "Seychelles" if country == "seychelles"
replace imfcode = 718 if country =="Seychelles"
replace country = "Sierra Leone" if country == "sierra_leone"
replace country = "Sierra Leone" if country == "sierraleone"
replace country = "Sierra Leone" if country == "SierraLeone"
replace imfcode = 724 if country =="Sierra Leone"
replace country = "Singapore" if country == "singapore"
replace country = "Singapore" if country == "SINGAPORE"
replace country = "Singapore" if country == "SG"
replace imfcode = 576 if country =="Singapore"
replace country = "Slovak Republic" if country == "slovak_rep"
replace country = "Slovak Republic" if country == "SlovakRepublic"
replace country = "Slovak Republic" if country == "slovakia"
replace country = "Slovak Republic" if country == "SK"
replace country = "Slovak Republic" if country == "Slovakia"
replace imfcode = 936 if country =="Slovak Republic"
replace country = "Slovenia" if country == "slovenia"
replace country = "Slovenia" if country == "SI"
replace imfcode = 961 if country =="Slovenia"
replace country = "Solomon Islands" if country == "solomon_is"
replace country = "Solomon Islands" if country == "Solomon Is."
replace country = "Solomon Islands" if country == "SolomonIslands"
replace imfcode = 813 if country =="Solomon Islands"
replace country = "Somalia" if country == "somalia"
replace imfcode = 726 if country =="Somalia"
replace country = "South Africa" if country == "south_africa"
replace country = "South Africa" if country == "southafrica"
replace country = "South Africa" if country == "S. Africa"
replace country = "South Africa" if country == "ZA"
replace country = "South Africa" if country == "SouthAfrica"
replace country = "South Africa" if country == "SOUTH AFRICA"
replace imfcode = 199 if country =="South Africa"
replace country = "Spain" if country == "spain"
replace country = "Spain" if country == "ES"
replace country = "Spain" if country == "SPAIN"
replace imfcode = 184 if country =="Spain"
replace country = "" if country == "sri_lanka"
replace country = "Sri Lanka" if country == "srilanka"
replace country = "Sri Lanka" if country == "SRI LANKA"
replace country = "Sri Lanka" if country == "Sri Lanka (Ceylon)"
replace country = "Sri Lanka" if country == "SriLanka"
replace imfcode = 524 if country =="Sri Lanka"
replace country = "St. Kitts and Nevis" if country == "st_kitts_n"
replace country = "St. Kitts and Nevis" if country == "Saint Kitts and Nevis"
replace country = "St. Kitts and Nevis" if country == "St.KittsandNevis"
replace country = "St. Kitts and Nevis" if country == "St. Kitts & Nevis"
replace imfcode = 361 if country =="St. Kitts and Nevis"
replace country = "St. Lucia" if country == "st_lucia"
replace country = "St. Lucia" if country == "St.Lucia"
replace imfcode = 362 if country =="St. Lucia"
replace country = "St. Vincent and the Grenadines" if country == "st_vincent_gr"
replace country = "St. Vincent and the Grenadines" if country == "Saint Vincent and the Grenadines"
replace country = "St. Vincent and the Grenadines" if country == "St.VincentandtheGrenadines"
replace country = "St. Vincent and the Grenadines" if country == "St. Vincent & Grenadine"
replace imfcode = 364 if country =="St. Vincent and the Grenadines"
replace country = "Sudan" if country == "sudan"
replace imfcode = 732 if country =="Sudan"
replace country = "Suriname" if country == "suriname"
replace country = "Suriname" if country == "Surinam"
replace imfcode = 366 if country =="Suriname"
replace country = "Swaziland" if country == "swaziland"
replace imfcode = 734 if country =="Swaziland"
replace country = "Sweden" if country == "sweden"
replace country = "Sweden" if country == "SWEDEN"
replace country = "Sweden" if country == "SE"
replace imfcode = 144 if country =="Sweden"
replace country = "Switzerland" if country == "switzerland"
replace country = "Switzerland" if country == "CH"
replace country = "Switzerland" if country == "SWITZERLAND"
replace imfcode = 146 if country =="Switzerland"
replace country = "Syria" if country == "syria"
replace country= "Syria" if country=="Syrian Arab Republic"
replace country= "Syria" if country=="SyrianArabRepublic"
replace imfcode = 463 if country =="Syria"
replace country = "Taiwan" if country == "taiwan"
replace country = "Taiwan" if country == "TW"
replace country = "Taiwan" if country == "Taiwan "
replace country = "Taiwan" if country == "Taiwan, China"
replace country = "Taiwan" if country == "Taiwan Province of China"
replace country = "Taiwan" if country == "TAIWAN"
replace imfcode = 528 if country == "Taiwan"
replace country = "Tajikistan" if country == "tajikistan"
replace imfcode = 923 if country =="Tajikistan"
replace country = "Tanzania" if country == "tanzania"
replace country = "Tanzania" if country == "TZ"
replace country = "Tanzania" if country == "Tanzania/Tanganyika"
replace imfcode = 738 if country =="Tanzania"
replace country = "Thailand" if country == "thailand"
replace country = "Thailand" if country == "TH"
replace country = "Thailand" if country == "THAILAND"
replace imfcode = 578 if country =="Thailand"
replace country = "Timor-Leste" if country == "Timor-Leste, Dem. Rep. of"
replace country = "Timor-Leste" if country == "East Timor"
replace imfcode = 537 if country =="Timor-Leste"
replace country = "Togo" if country == "togo"
replace imfcode = 742 if country =="Togo"
replace country = "Tonga" if country == "tonga"
replace imfcode = 866 if country =="Tonga"
replace country = "Trinidad and Tobago" if country == "trinidad_tob"
replace country = "Trinidad and Tobago" if country == "TT"
replace country = "Trinidad and Tobago" if country == "trinidadandtobago"
replace country = "Trinidad and Tobago" if country == "Trinidad-Tobago"
replace country = "Trinidad and Tobago" if country == "Trinidad"
replace country = "Trinidad and Tobago" if country == "Trinidad & Tobago"
replace country = "Trinidad and Tobago" if country == "TrinidadandTobago"
replace imfcode = 369 if country =="Trinidad and Tobago"
replace country = "Tunisia" if country == "tunisia"
replace imfcode = 744 if country =="Tunisia"
replace country = "Turkey" if country == "turkey"
replace country = "Turkey" if country == "TURKEY"
replace country = "Turkey" if country == "TR"
replace country = "Turkey" if country == "Turkey/Ottoman Empire"
replace imfcode = 186 if country =="Turkey"
replace country = "Turkmenistan" if country == "turkmenistan"
replace imfcode = 925 if country =="Turkmenistan"
replace country = "Uganda" if country == "uganda"
replace country = "Uganda" if country == "UG"
replace imfcode = 746 if country =="Uganda"
replace country = "Ukraine" if country == "ukraine"
replace country = "Ukraine" if country == "UA"
replace imfcode = 926 if country =="Ukraine"
replace country = "United Arab Emirates" if country == "uae"
replace country = "United Arab Emirates" if country == "UnitedArabEmirates"
replace country = "United Arab Emirates" if country == "UAE"
replace imfcode = 466 if country =="United Arab Emirates"
replace country = "United Kingdom" if country == "UK"
replace country = "United Kingdom" if country == "GB"
replace country = "United Kingdom" if country == "uk"
replace country = "United Kingdom" if country == "UNITED KINGDOM"
replace country = "United Kingdom" if country == "UnitedKingdom"
replace imfcode = 112 if country =="United Kingdom"
replace country = "United States" if country == "us"
replace country = "United States" if country == "UNITED STATES"
replace country = "United States" if country == "US"
replace country = "United States" if country == "USA"
replace country = "United States" if country == "UnitedStates"
replace country = "United States" if country == "United States of America"
replace imfcode = 111 if country =="United States"
replace country = "USSR" if country == "ussr"
replace country = "Uruguay" if country == "Uraguay"
replace country = "Uruguay" if country == "UY"
replace country = "Uruguay" if country == "uruguay"
replace country = "Uruguay" if country == "URUGUAY"
replace imfcode = 298 if country =="Uruguay"
replace country = "Uzbekistan" if country == "uzbekistan"
replace imfcode = 927 if country =="Uzbekistan"
replace country = "Vanuatu" if country == "vanuatu"
replace imfcode = 846 if country =="Vanuatu"
replace country = "Venezuela" if country == "venezuela"
replace country = "Venezuela" if country == "VE"
replace country = "Venezuela" if country == "Venezuela, RB"
replace country = "Venezuela" if country == " Venezuela, RB "
replace country = "Venezuela" if country == "Venezuela,RB"
replace country = "Venezuela" if country == "VENEZUELA"
replace country = "Venezuela" if country == "Venezuela, R.B. de"
replace imfcode = 299 if country =="Venezuela"
replace country = "Vietnam" if country == "viet_nam"
replace country = "Vietnam" if country == "VN"
replace country = "Vietnam" if country == "vietnam"
replace country = "Vietnam" if country == "Vietnam North"
replace country = "Vietnam" if country == "North Vietnam"
replace country = "Vietnam_Dem_Rep" if country == "Vietnam, Democratic Republic of"
replace imfcode = 582 if country =="Vietnam"
replace country = "Virgin Islands (U.S.)" if country == "virgin_is"
replace country = "Virgin Islands (U.S.)" if country == "Virgin Islands (U.S.)"
replace country = "Virgin Islands (U.S.)" if country == "VirginIslands(U.S.)"
replace imfcode = . if country =="Virgin Islands (U.S.)"
replace country = "West Bank and Gaza" if country == "west_bank_g"
replace country = "West Bank and Gaza" if country == "wbankgaza"
replace country = "West Bank and Gaza" if country == "WestBankandGaza"
replace imfcode = 487 if country =="West Bank and Gaza"
replace country = "Yemen" if country == "yemen"
replace country = "Yemen" if country =="Yemen, Rep."
replace country = "Yemen" if country ==" Yemen, Rep. "
replace country = "Yemen" if country =="Yemen,Rep."
replace country = "Yemen" if country =="Yemen, Rep. of"
replace country = "Yemen" if country =="Yemen, Republic of"
replace imfcode = 474 if country =="Yemen"
replace country = "Yugoslavia" if country == "yugoslavia"
replace country = "Zambia" if country == "zambia"
replace country = "Zambia" if country == "ZM"
replace imfcode = 754 if country =="Zambia"
replace country = "Zimbabwe" if country == "zimbabwe"
replace country = "Zimbabwe" if country == "ZIMBABWE"
replace country = "Zimbabwe" if country == "ZW"
replace country = "Zimbabwe" if country == "Zimbabwe (Rhodesia)" 
replace imfcode = 698 if country =="Zimbabwe"

